//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Player/Inputs/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Main"",
            ""id"": ""28179ff4-ba6d-4eef-a668-cd749e22b5da"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""183ca19d-88d1-49c8-8553-15a7080908d9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveLeftRight"",
                    ""type"": ""Button"",
                    ""id"": ""30087a9b-cce3-4270-8646-7afe4e3a580f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveForwardBackward"",
                    ""type"": ""Button"",
                    ""id"": ""8b3e3a17-2c8c-4295-a4db-425f507b03d0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pickup"",
                    ""type"": ""Button"",
                    ""id"": ""0c2b8020-1c93-47ad-a799-463f75f4d804"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventoryOpenClose"",
                    ""type"": ""Button"",
                    ""id"": ""40cb19e7-300a-4598-baf8-ca0377f627b3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SplitItemByTwoParts"",
                    ""type"": ""Button"",
                    ""id"": ""0e8d0aba-66e1-447b-81e4-2a6230c7563c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActivateFirstItem"",
                    ""type"": ""Button"",
                    ""id"": ""3765facd-0929-4d1f-82a2-2aa09742235c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActivateSecondItem"",
                    ""type"": ""Button"",
                    ""id"": ""abeffc83-0418-46f4-9d38-506a4c2d45db"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActivateThirdItem"",
                    ""type"": ""Button"",
                    ""id"": ""61dd8844-fa44-4843-a047-3ff663d7ac1d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActivateFourthItem"",
                    ""type"": ""Button"",
                    ""id"": ""426223fc-05ab-4dd0-918d-9eab8dc3a354"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActivateFifthItem"",
                    ""type"": ""Button"",
                    ""id"": ""8077865a-4284-40f3-a9ac-2b81eeb22219"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActivateSixthItem"",
                    ""type"": ""Button"",
                    ""id"": ""ca595074-ad0a-4293-a560-d61dbc3a60dd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActivateSeventhItem"",
                    ""type"": ""Button"",
                    ""id"": ""75a89365-c417-4939-a042-0d2a01808781"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActivateEightItem"",
                    ""type"": ""Button"",
                    ""id"": ""9048f6ed-def6-4cb9-87a4-04ddf576446c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""cf316533-a8ea-4105-98a5-b02d83ba3610"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ItemAttack"",
                    ""type"": ""Button"",
                    ""id"": ""75acee08-5dd0-4329-b392-907db4085d4e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""f9729551-629c-49f4-87d7-96fdd1a2c3dd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""427ea66b-e549-4865-b352-f333471c4f7a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""659d42e4-2e22-4d0f-b441-cdcc60270d8d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slide"",
                    ""type"": ""Button"",
                    ""id"": ""baabccf1-0cb8-421e-90e6-fe56680f1dfe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeaponSelectionWheel"",
                    ""type"": ""Button"",
                    ""id"": ""200cb93a-85bb-4dd9-903e-d44a1f075548"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseLook"",
                    ""type"": ""Value"",
                    ""id"": ""7cd3b7fb-c180-4b36-a119-b2bdae055335"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PlaceFlask"",
                    ""type"": ""Button"",
                    ""id"": ""45105499-e24e-4e40-bb6a-024931cd2766"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThrowJumpad"",
                    ""type"": ""Button"",
                    ""id"": ""9e370e5e-4255-448f-ae09-d268e7040fd6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FlaskTakeHide"",
                    ""type"": ""Button"",
                    ""id"": ""ada725b5-73e5-43c4-aa3b-09aa9e7f9283"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThrowHook"",
                    ""type"": ""Button"",
                    ""id"": ""d3a3796a-37d2-4b48-9640-1c2d04d3d2aa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Settings"",
                    ""type"": ""Button"",
                    ""id"": ""0fe39f82-b74c-4502-9ecd-4765fbce83f9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GamepadRadialWheel"",
                    ""type"": ""Value"",
                    ""id"": ""a897d24c-fab9-4078-a844-d2f885af5cd4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""EarthquakeDash"",
                    ""type"": ""Button"",
                    ""id"": ""4da3add8-93a6-4fb4-8138-edbdb6f357f9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GravityHandling"",
                    ""type"": ""Button"",
                    ""id"": ""4daf935e-79e8-4c5b-9c6e-e4354257a3bc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GravityGunImpulse"",
                    ""type"": ""Button"",
                    ""id"": ""d1f3402d-1f02-4dd1-b3d8-6090769b57f0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9970d99f-65b2-47ea-8e50-24d45f2af37d"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""27d4d7a3-2fef-450b-b461-297e86292899"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""LeftRight"",
                    ""id"": ""431c994a-e633-4e1e-8ea7-eed7e3e02fb5"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeftRight"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""9c0b116d-6f7e-41b8-8901-f59beb9cff33"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""MoveLeftRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""58406d22-c466-468c-85c8-f764d6c64fe2"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""MoveLeftRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""LeftRight"",
                    ""id"": ""47298e60-5f05-4b9f-8a18-842f77d105cf"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeftRight"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""24eb442c-90b9-47ec-b49e-da8a07926946"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeftRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""b516aff1-997d-4ff2-b08b-fb9a3f42e587"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeftRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""ForwardBackward"",
                    ""id"": ""fc007c3b-49b4-4d1e-8655-9e2b814e1ef7"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveForwardBackward"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""e2a4d554-5199-451b-8fa3-7344ab2acb99"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveForwardBackward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""bf13b3e2-e8da-42e9-9d83-9905f5389689"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveForwardBackward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""ForwardBackward"",
                    ""id"": ""560c1be3-5462-4569-8533-f8528d080c84"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveForwardBackward"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""e6a7d880-8b02-40e1-a21c-2724dc0c3e53"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveForwardBackward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""b5c1c378-d2b4-48d7-80ad-626ff363b567"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveForwardBackward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f5e0722b-a7c3-4f20-a525-db5ff155b791"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pickup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15ed3fc6-d205-46c6-b014-daf8b1865a86"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pickup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90050b3e-56b8-4818-b54b-3347256d02d4"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryOpenClose"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ef14066a-ec95-4a2c-b5c9-21554ce240db"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SplitItemByTwoParts"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30a0c8a9-07ed-4696-8b69-2ece2b60df95"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActivateFirstItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6df913bf-c3ce-44a8-a2d6-646215b23291"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActivateSecondItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9757b61-d2af-47a8-8817-21fb0a6c5a41"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActivateThirdItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5c27353-659d-4f08-858b-168a1e0ba258"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActivateFourthItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3cbbcd0d-045f-45a1-921a-92ded11d2fba"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActivateFifthItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""159bbee1-5563-47d3-89e9-1aa4d53ca6c4"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActivateSixthItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea3d1002-40f5-4dad-b634-6359bd2d7656"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActivateSeventhItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""315c224b-71a1-4a3b-9277-50bae1488794"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0fc27cc9-447a-44be-8c63-e94b9f8240ec"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ItemAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b4fbccb-fd38-4f20-a675-dc95ed62b551"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c88456c-9800-4202-8e97-76b7f859bb19"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ee07ef2-5810-4818-8b0a-b7969b566bf3"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f29ccaa1-d5a9-4322-91d7-10019f87bed6"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""27449ab4-3d53-49aa-bb02-966fa042bb99"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8b57ca8-2943-4446-b620-e17b800f09df"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""20028869-183a-42a4-b047-753ef0218fad"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cfa3ae90-db08-4583-84c3-cada1e8c0394"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponSelectionWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ada5d2d-2cb8-45a7-9d85-966d809dbfc4"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponSelectionWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4327e82c-1526-410c-9f25-e32b03f1f648"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72858b5a-c026-473d-bc24-ad39204c872d"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=65,y=65)"",
                    ""groups"": """",
                    ""action"": ""MouseLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37fd86c9-4124-4adf-b7cb-f41a569c42f0"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceFlask"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3fb3420f-4049-42f0-bffe-8d1ccd6466bf"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceFlask"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2d0d0e4-2be5-4770-8b28-5f06254cd6eb"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrowJumpad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a266443-81c1-4122-9641-8838f2b57787"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrowJumpad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88eaf3f3-b971-426d-8b55-1ce0f3ffa30a"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FlaskTakeHide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df18cd4c-0611-40ce-9829-c3ab32626157"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FlaskTakeHide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d86645c6-48e8-40c8-a6d4-36c68a1f3f0a"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActivateEightItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54a73a41-6e3b-48e1-9395-c9274562dda2"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrowHook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a9a6ed8-a6ca-4ecc-9aa1-87bc30be04fb"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrowHook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d01a27ff-3dd5-4016-9d01-2f10b997148d"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Settings"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""98f64528-fa64-48da-86b4-3c2cce4159e4"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GamepadRadialWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e900983-a4ff-4f36-a985-1c08afed5a36"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EarthquakeDash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77dc87c3-501f-4ccb-9d52-8db4459d2dbe"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GravityHandling"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c45b9f1-6c6e-4b59-9190-482df55e777e"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GravityGunImpulse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""PC"",
            ""bindingGroup"": ""PC"",
            ""devices"": []
        }
    ]
}");
        // Main
        m_Main = asset.FindActionMap("Main", throwIfNotFound: true);
        m_Main_Jump = m_Main.FindAction("Jump", throwIfNotFound: true);
        m_Main_MoveLeftRight = m_Main.FindAction("MoveLeftRight", throwIfNotFound: true);
        m_Main_MoveForwardBackward = m_Main.FindAction("MoveForwardBackward", throwIfNotFound: true);
        m_Main_Pickup = m_Main.FindAction("Pickup", throwIfNotFound: true);
        m_Main_InventoryOpenClose = m_Main.FindAction("InventoryOpenClose", throwIfNotFound: true);
        m_Main_SplitItemByTwoParts = m_Main.FindAction("SplitItemByTwoParts", throwIfNotFound: true);
        m_Main_ActivateFirstItem = m_Main.FindAction("ActivateFirstItem", throwIfNotFound: true);
        m_Main_ActivateSecondItem = m_Main.FindAction("ActivateSecondItem", throwIfNotFound: true);
        m_Main_ActivateThirdItem = m_Main.FindAction("ActivateThirdItem", throwIfNotFound: true);
        m_Main_ActivateFourthItem = m_Main.FindAction("ActivateFourthItem", throwIfNotFound: true);
        m_Main_ActivateFifthItem = m_Main.FindAction("ActivateFifthItem", throwIfNotFound: true);
        m_Main_ActivateSixthItem = m_Main.FindAction("ActivateSixthItem", throwIfNotFound: true);
        m_Main_ActivateSeventhItem = m_Main.FindAction("ActivateSeventhItem", throwIfNotFound: true);
        m_Main_ActivateEightItem = m_Main.FindAction("ActivateEightItem", throwIfNotFound: true);
        m_Main_Run = m_Main.FindAction("Run", throwIfNotFound: true);
        m_Main_ItemAttack = m_Main.FindAction("ItemAttack", throwIfNotFound: true);
        m_Main_Shoot = m_Main.FindAction("Shoot", throwIfNotFound: true);
        m_Main_Reload = m_Main.FindAction("Reload", throwIfNotFound: true);
        m_Main_Dash = m_Main.FindAction("Dash", throwIfNotFound: true);
        m_Main_Slide = m_Main.FindAction("Slide", throwIfNotFound: true);
        m_Main_WeaponSelectionWheel = m_Main.FindAction("WeaponSelectionWheel", throwIfNotFound: true);
        m_Main_MouseLook = m_Main.FindAction("MouseLook", throwIfNotFound: true);
        m_Main_PlaceFlask = m_Main.FindAction("PlaceFlask", throwIfNotFound: true);
        m_Main_ThrowJumpad = m_Main.FindAction("ThrowJumpad", throwIfNotFound: true);
        m_Main_FlaskTakeHide = m_Main.FindAction("FlaskTakeHide", throwIfNotFound: true);
        m_Main_ThrowHook = m_Main.FindAction("ThrowHook", throwIfNotFound: true);
        m_Main_Settings = m_Main.FindAction("Settings", throwIfNotFound: true);
        m_Main_GamepadRadialWheel = m_Main.FindAction("GamepadRadialWheel", throwIfNotFound: true);
        m_Main_EarthquakeDash = m_Main.FindAction("EarthquakeDash", throwIfNotFound: true);
        m_Main_GravityHandling = m_Main.FindAction("GravityHandling", throwIfNotFound: true);
        m_Main_GravityGunImpulse = m_Main.FindAction("GravityGunImpulse", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Main
    private readonly InputActionMap m_Main;
    private IMainActions m_MainActionsCallbackInterface;
    private readonly InputAction m_Main_Jump;
    private readonly InputAction m_Main_MoveLeftRight;
    private readonly InputAction m_Main_MoveForwardBackward;
    private readonly InputAction m_Main_Pickup;
    private readonly InputAction m_Main_InventoryOpenClose;
    private readonly InputAction m_Main_SplitItemByTwoParts;
    private readonly InputAction m_Main_ActivateFirstItem;
    private readonly InputAction m_Main_ActivateSecondItem;
    private readonly InputAction m_Main_ActivateThirdItem;
    private readonly InputAction m_Main_ActivateFourthItem;
    private readonly InputAction m_Main_ActivateFifthItem;
    private readonly InputAction m_Main_ActivateSixthItem;
    private readonly InputAction m_Main_ActivateSeventhItem;
    private readonly InputAction m_Main_ActivateEightItem;
    private readonly InputAction m_Main_Run;
    private readonly InputAction m_Main_ItemAttack;
    private readonly InputAction m_Main_Shoot;
    private readonly InputAction m_Main_Reload;
    private readonly InputAction m_Main_Dash;
    private readonly InputAction m_Main_Slide;
    private readonly InputAction m_Main_WeaponSelectionWheel;
    private readonly InputAction m_Main_MouseLook;
    private readonly InputAction m_Main_PlaceFlask;
    private readonly InputAction m_Main_ThrowJumpad;
    private readonly InputAction m_Main_FlaskTakeHide;
    private readonly InputAction m_Main_ThrowHook;
    private readonly InputAction m_Main_Settings;
    private readonly InputAction m_Main_GamepadRadialWheel;
    private readonly InputAction m_Main_EarthquakeDash;
    private readonly InputAction m_Main_GravityHandling;
    private readonly InputAction m_Main_GravityGunImpulse;
    public struct MainActions
    {
        private @PlayerControls m_Wrapper;
        public MainActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_Main_Jump;
        public InputAction @MoveLeftRight => m_Wrapper.m_Main_MoveLeftRight;
        public InputAction @MoveForwardBackward => m_Wrapper.m_Main_MoveForwardBackward;
        public InputAction @Pickup => m_Wrapper.m_Main_Pickup;
        public InputAction @InventoryOpenClose => m_Wrapper.m_Main_InventoryOpenClose;
        public InputAction @SplitItemByTwoParts => m_Wrapper.m_Main_SplitItemByTwoParts;
        public InputAction @ActivateFirstItem => m_Wrapper.m_Main_ActivateFirstItem;
        public InputAction @ActivateSecondItem => m_Wrapper.m_Main_ActivateSecondItem;
        public InputAction @ActivateThirdItem => m_Wrapper.m_Main_ActivateThirdItem;
        public InputAction @ActivateFourthItem => m_Wrapper.m_Main_ActivateFourthItem;
        public InputAction @ActivateFifthItem => m_Wrapper.m_Main_ActivateFifthItem;
        public InputAction @ActivateSixthItem => m_Wrapper.m_Main_ActivateSixthItem;
        public InputAction @ActivateSeventhItem => m_Wrapper.m_Main_ActivateSeventhItem;
        public InputAction @ActivateEightItem => m_Wrapper.m_Main_ActivateEightItem;
        public InputAction @Run => m_Wrapper.m_Main_Run;
        public InputAction @ItemAttack => m_Wrapper.m_Main_ItemAttack;
        public InputAction @Shoot => m_Wrapper.m_Main_Shoot;
        public InputAction @Reload => m_Wrapper.m_Main_Reload;
        public InputAction @Dash => m_Wrapper.m_Main_Dash;
        public InputAction @Slide => m_Wrapper.m_Main_Slide;
        public InputAction @WeaponSelectionWheel => m_Wrapper.m_Main_WeaponSelectionWheel;
        public InputAction @MouseLook => m_Wrapper.m_Main_MouseLook;
        public InputAction @PlaceFlask => m_Wrapper.m_Main_PlaceFlask;
        public InputAction @ThrowJumpad => m_Wrapper.m_Main_ThrowJumpad;
        public InputAction @FlaskTakeHide => m_Wrapper.m_Main_FlaskTakeHide;
        public InputAction @ThrowHook => m_Wrapper.m_Main_ThrowHook;
        public InputAction @Settings => m_Wrapper.m_Main_Settings;
        public InputAction @GamepadRadialWheel => m_Wrapper.m_Main_GamepadRadialWheel;
        public InputAction @EarthquakeDash => m_Wrapper.m_Main_EarthquakeDash;
        public InputAction @GravityHandling => m_Wrapper.m_Main_GravityHandling;
        public InputAction @GravityGunImpulse => m_Wrapper.m_Main_GravityGunImpulse;
        public InputActionMap Get() { return m_Wrapper.m_Main; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainActions set) { return set.Get(); }
        public void SetCallbacks(IMainActions instance)
        {
            if (m_Wrapper.m_MainActionsCallbackInterface != null)
            {
                @Jump.started -= m_Wrapper.m_MainActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnJump;
                @MoveLeftRight.started -= m_Wrapper.m_MainActionsCallbackInterface.OnMoveLeftRight;
                @MoveLeftRight.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnMoveLeftRight;
                @MoveLeftRight.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnMoveLeftRight;
                @MoveForwardBackward.started -= m_Wrapper.m_MainActionsCallbackInterface.OnMoveForwardBackward;
                @MoveForwardBackward.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnMoveForwardBackward;
                @MoveForwardBackward.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnMoveForwardBackward;
                @Pickup.started -= m_Wrapper.m_MainActionsCallbackInterface.OnPickup;
                @Pickup.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnPickup;
                @Pickup.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnPickup;
                @InventoryOpenClose.started -= m_Wrapper.m_MainActionsCallbackInterface.OnInventoryOpenClose;
                @InventoryOpenClose.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnInventoryOpenClose;
                @InventoryOpenClose.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnInventoryOpenClose;
                @SplitItemByTwoParts.started -= m_Wrapper.m_MainActionsCallbackInterface.OnSplitItemByTwoParts;
                @SplitItemByTwoParts.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnSplitItemByTwoParts;
                @SplitItemByTwoParts.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnSplitItemByTwoParts;
                @ActivateFirstItem.started -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateFirstItem;
                @ActivateFirstItem.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateFirstItem;
                @ActivateFirstItem.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateFirstItem;
                @ActivateSecondItem.started -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateSecondItem;
                @ActivateSecondItem.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateSecondItem;
                @ActivateSecondItem.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateSecondItem;
                @ActivateThirdItem.started -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateThirdItem;
                @ActivateThirdItem.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateThirdItem;
                @ActivateThirdItem.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateThirdItem;
                @ActivateFourthItem.started -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateFourthItem;
                @ActivateFourthItem.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateFourthItem;
                @ActivateFourthItem.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateFourthItem;
                @ActivateFifthItem.started -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateFifthItem;
                @ActivateFifthItem.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateFifthItem;
                @ActivateFifthItem.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateFifthItem;
                @ActivateSixthItem.started -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateSixthItem;
                @ActivateSixthItem.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateSixthItem;
                @ActivateSixthItem.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateSixthItem;
                @ActivateSeventhItem.started -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateSeventhItem;
                @ActivateSeventhItem.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateSeventhItem;
                @ActivateSeventhItem.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateSeventhItem;
                @ActivateEightItem.started -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateEightItem;
                @ActivateEightItem.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateEightItem;
                @ActivateEightItem.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnActivateEightItem;
                @Run.started -= m_Wrapper.m_MainActionsCallbackInterface.OnRun;
                @Run.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnRun;
                @Run.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnRun;
                @ItemAttack.started -= m_Wrapper.m_MainActionsCallbackInterface.OnItemAttack;
                @ItemAttack.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnItemAttack;
                @ItemAttack.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnItemAttack;
                @Shoot.started -= m_Wrapper.m_MainActionsCallbackInterface.OnShoot;
                @Shoot.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnShoot;
                @Shoot.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnShoot;
                @Reload.started -= m_Wrapper.m_MainActionsCallbackInterface.OnReload;
                @Reload.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnReload;
                @Reload.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnReload;
                @Dash.started -= m_Wrapper.m_MainActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnDash;
                @Slide.started -= m_Wrapper.m_MainActionsCallbackInterface.OnSlide;
                @Slide.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnSlide;
                @Slide.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnSlide;
                @WeaponSelectionWheel.started -= m_Wrapper.m_MainActionsCallbackInterface.OnWeaponSelectionWheel;
                @WeaponSelectionWheel.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnWeaponSelectionWheel;
                @WeaponSelectionWheel.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnWeaponSelectionWheel;
                @MouseLook.started -= m_Wrapper.m_MainActionsCallbackInterface.OnMouseLook;
                @MouseLook.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnMouseLook;
                @MouseLook.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnMouseLook;
                @PlaceFlask.started -= m_Wrapper.m_MainActionsCallbackInterface.OnPlaceFlask;
                @PlaceFlask.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnPlaceFlask;
                @PlaceFlask.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnPlaceFlask;
                @ThrowJumpad.started -= m_Wrapper.m_MainActionsCallbackInterface.OnThrowJumpad;
                @ThrowJumpad.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnThrowJumpad;
                @ThrowJumpad.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnThrowJumpad;
                @FlaskTakeHide.started -= m_Wrapper.m_MainActionsCallbackInterface.OnFlaskTakeHide;
                @FlaskTakeHide.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnFlaskTakeHide;
                @FlaskTakeHide.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnFlaskTakeHide;
                @ThrowHook.started -= m_Wrapper.m_MainActionsCallbackInterface.OnThrowHook;
                @ThrowHook.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnThrowHook;
                @ThrowHook.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnThrowHook;
                @Settings.started -= m_Wrapper.m_MainActionsCallbackInterface.OnSettings;
                @Settings.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnSettings;
                @Settings.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnSettings;
                @GamepadRadialWheel.started -= m_Wrapper.m_MainActionsCallbackInterface.OnGamepadRadialWheel;
                @GamepadRadialWheel.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnGamepadRadialWheel;
                @GamepadRadialWheel.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnGamepadRadialWheel;
                @EarthquakeDash.started -= m_Wrapper.m_MainActionsCallbackInterface.OnEarthquakeDash;
                @EarthquakeDash.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnEarthquakeDash;
                @EarthquakeDash.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnEarthquakeDash;
                @GravityHandling.started -= m_Wrapper.m_MainActionsCallbackInterface.OnGravityHandling;
                @GravityHandling.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnGravityHandling;
                @GravityHandling.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnGravityHandling;
                @GravityGunImpulse.started -= m_Wrapper.m_MainActionsCallbackInterface.OnGravityGunImpulse;
                @GravityGunImpulse.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnGravityGunImpulse;
                @GravityGunImpulse.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnGravityGunImpulse;
            }
            m_Wrapper.m_MainActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @MoveLeftRight.started += instance.OnMoveLeftRight;
                @MoveLeftRight.performed += instance.OnMoveLeftRight;
                @MoveLeftRight.canceled += instance.OnMoveLeftRight;
                @MoveForwardBackward.started += instance.OnMoveForwardBackward;
                @MoveForwardBackward.performed += instance.OnMoveForwardBackward;
                @MoveForwardBackward.canceled += instance.OnMoveForwardBackward;
                @Pickup.started += instance.OnPickup;
                @Pickup.performed += instance.OnPickup;
                @Pickup.canceled += instance.OnPickup;
                @InventoryOpenClose.started += instance.OnInventoryOpenClose;
                @InventoryOpenClose.performed += instance.OnInventoryOpenClose;
                @InventoryOpenClose.canceled += instance.OnInventoryOpenClose;
                @SplitItemByTwoParts.started += instance.OnSplitItemByTwoParts;
                @SplitItemByTwoParts.performed += instance.OnSplitItemByTwoParts;
                @SplitItemByTwoParts.canceled += instance.OnSplitItemByTwoParts;
                @ActivateFirstItem.started += instance.OnActivateFirstItem;
                @ActivateFirstItem.performed += instance.OnActivateFirstItem;
                @ActivateFirstItem.canceled += instance.OnActivateFirstItem;
                @ActivateSecondItem.started += instance.OnActivateSecondItem;
                @ActivateSecondItem.performed += instance.OnActivateSecondItem;
                @ActivateSecondItem.canceled += instance.OnActivateSecondItem;
                @ActivateThirdItem.started += instance.OnActivateThirdItem;
                @ActivateThirdItem.performed += instance.OnActivateThirdItem;
                @ActivateThirdItem.canceled += instance.OnActivateThirdItem;
                @ActivateFourthItem.started += instance.OnActivateFourthItem;
                @ActivateFourthItem.performed += instance.OnActivateFourthItem;
                @ActivateFourthItem.canceled += instance.OnActivateFourthItem;
                @ActivateFifthItem.started += instance.OnActivateFifthItem;
                @ActivateFifthItem.performed += instance.OnActivateFifthItem;
                @ActivateFifthItem.canceled += instance.OnActivateFifthItem;
                @ActivateSixthItem.started += instance.OnActivateSixthItem;
                @ActivateSixthItem.performed += instance.OnActivateSixthItem;
                @ActivateSixthItem.canceled += instance.OnActivateSixthItem;
                @ActivateSeventhItem.started += instance.OnActivateSeventhItem;
                @ActivateSeventhItem.performed += instance.OnActivateSeventhItem;
                @ActivateSeventhItem.canceled += instance.OnActivateSeventhItem;
                @ActivateEightItem.started += instance.OnActivateEightItem;
                @ActivateEightItem.performed += instance.OnActivateEightItem;
                @ActivateEightItem.canceled += instance.OnActivateEightItem;
                @Run.started += instance.OnRun;
                @Run.performed += instance.OnRun;
                @Run.canceled += instance.OnRun;
                @ItemAttack.started += instance.OnItemAttack;
                @ItemAttack.performed += instance.OnItemAttack;
                @ItemAttack.canceled += instance.OnItemAttack;
                @Shoot.started += instance.OnShoot;
                @Shoot.performed += instance.OnShoot;
                @Shoot.canceled += instance.OnShoot;
                @Reload.started += instance.OnReload;
                @Reload.performed += instance.OnReload;
                @Reload.canceled += instance.OnReload;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @Slide.started += instance.OnSlide;
                @Slide.performed += instance.OnSlide;
                @Slide.canceled += instance.OnSlide;
                @WeaponSelectionWheel.started += instance.OnWeaponSelectionWheel;
                @WeaponSelectionWheel.performed += instance.OnWeaponSelectionWheel;
                @WeaponSelectionWheel.canceled += instance.OnWeaponSelectionWheel;
                @MouseLook.started += instance.OnMouseLook;
                @MouseLook.performed += instance.OnMouseLook;
                @MouseLook.canceled += instance.OnMouseLook;
                @PlaceFlask.started += instance.OnPlaceFlask;
                @PlaceFlask.performed += instance.OnPlaceFlask;
                @PlaceFlask.canceled += instance.OnPlaceFlask;
                @ThrowJumpad.started += instance.OnThrowJumpad;
                @ThrowJumpad.performed += instance.OnThrowJumpad;
                @ThrowJumpad.canceled += instance.OnThrowJumpad;
                @FlaskTakeHide.started += instance.OnFlaskTakeHide;
                @FlaskTakeHide.performed += instance.OnFlaskTakeHide;
                @FlaskTakeHide.canceled += instance.OnFlaskTakeHide;
                @ThrowHook.started += instance.OnThrowHook;
                @ThrowHook.performed += instance.OnThrowHook;
                @ThrowHook.canceled += instance.OnThrowHook;
                @Settings.started += instance.OnSettings;
                @Settings.performed += instance.OnSettings;
                @Settings.canceled += instance.OnSettings;
                @GamepadRadialWheel.started += instance.OnGamepadRadialWheel;
                @GamepadRadialWheel.performed += instance.OnGamepadRadialWheel;
                @GamepadRadialWheel.canceled += instance.OnGamepadRadialWheel;
                @EarthquakeDash.started += instance.OnEarthquakeDash;
                @EarthquakeDash.performed += instance.OnEarthquakeDash;
                @EarthquakeDash.canceled += instance.OnEarthquakeDash;
                @GravityHandling.started += instance.OnGravityHandling;
                @GravityHandling.performed += instance.OnGravityHandling;
                @GravityHandling.canceled += instance.OnGravityHandling;
                @GravityGunImpulse.started += instance.OnGravityGunImpulse;
                @GravityGunImpulse.performed += instance.OnGravityGunImpulse;
                @GravityGunImpulse.canceled += instance.OnGravityGunImpulse;
            }
        }
    }
    public MainActions @Main => new MainActions(this);
    private int m_PCSchemeIndex = -1;
    public InputControlScheme PCScheme
    {
        get
        {
            if (m_PCSchemeIndex == -1) m_PCSchemeIndex = asset.FindControlSchemeIndex("PC");
            return asset.controlSchemes[m_PCSchemeIndex];
        }
    }
    public interface IMainActions
    {
        void OnJump(InputAction.CallbackContext context);
        void OnMoveLeftRight(InputAction.CallbackContext context);
        void OnMoveForwardBackward(InputAction.CallbackContext context);
        void OnPickup(InputAction.CallbackContext context);
        void OnInventoryOpenClose(InputAction.CallbackContext context);
        void OnSplitItemByTwoParts(InputAction.CallbackContext context);
        void OnActivateFirstItem(InputAction.CallbackContext context);
        void OnActivateSecondItem(InputAction.CallbackContext context);
        void OnActivateThirdItem(InputAction.CallbackContext context);
        void OnActivateFourthItem(InputAction.CallbackContext context);
        void OnActivateFifthItem(InputAction.CallbackContext context);
        void OnActivateSixthItem(InputAction.CallbackContext context);
        void OnActivateSeventhItem(InputAction.CallbackContext context);
        void OnActivateEightItem(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnItemAttack(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnSlide(InputAction.CallbackContext context);
        void OnWeaponSelectionWheel(InputAction.CallbackContext context);
        void OnMouseLook(InputAction.CallbackContext context);
        void OnPlaceFlask(InputAction.CallbackContext context);
        void OnThrowJumpad(InputAction.CallbackContext context);
        void OnFlaskTakeHide(InputAction.CallbackContext context);
        void OnThrowHook(InputAction.CallbackContext context);
        void OnSettings(InputAction.CallbackContext context);
        void OnGamepadRadialWheel(InputAction.CallbackContext context);
        void OnEarthquakeDash(InputAction.CallbackContext context);
        void OnGravityHandling(InputAction.CallbackContext context);
        void OnGravityGunImpulse(InputAction.CallbackContext context);
    }
}
